libreria/urls.py
from django.urls.conf import path
from .views import LibroList_CS, AutoreDetail_CS, AutoreList_CS

app_name = "libreria"

urlpatterns = [
    path("", LibroList_CS.as_view(), name="lista_libri"),
    path("autori/<int:pk>", AutoreDetail_CS.as_view(), name="autore_detail"),
    path("autori", AutoreList_CS.as_view(), name="lista_autori")
]

news/urls.py
from os import name
from news.models import Giornalista
from django.urls import path
from .views import home, ArticoloDetailViewCB, ArticoloListView, GiornalistaDetailViewCB, GiornalistaListView

app_name = "news"

urlpatterns = [
    path("", home, name="homeview"),
    path("articoli/<int:pk>", ArticoloDetailViewCB.as_view(), name="articolo_detail"),
    path("lista_articoli/", ArticoloListView.as_view(), name="lista_articoli"),
    path("giornalista/<int:pk>", GiornalistaDetailViewCB.as_view(),
         name="giornalista_detail"),
    path("lista_giornalisti/", GiornalistaListView.as_view(),
         name="lista_giornalisti")
]

prima_app/urls.py
from django.urls import path
from .views import homepage, menu, chisiamo, variabili, index

app_name = "prima_app"
urlpatterns = [
    path("welcome/", homepage, name="homepage"),
    path("menu/", menu, name="menu"),
    path("chi-siamo/", chisiamo, name="chi-siamo"),
    path("variabili/", variabili, name="variabili"),
    path("index", index, name="index")
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path, include
from prima_app.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("prima_app/", include("prima_app.urls")),
    path("seconda_app/", include("seconda_app.urls")),
    path("news/", include("news.urls")),
    path("libreria/", include("libreria.urls")),
    path("", index, name="index")
]

seconda_app/urls.py
from django.urls import path
from .views import esif, ifelse, ifelif, esfor

app_name = "seconda_app"
urlpatterns = [
    path("if/", esif, name="if"),
    path("ifelse/", ifelse, name="ifelse"),
    path("ifelif/", ifelif, name="ifelif"),
    path("for/", esfor, name="for"),
]

libreria/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Genere_CS(models.Model):
    nome = models.CharField(max_length=20)

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = "Genere"
        verbose_name_plural = "Generi"


class Autore_CS(models.Model):
    nome = models.CharField(max_length=20)
    cognome = models.CharField(max_length=20)
    nazione = models.CharField(max_length=20)

    def __str__(self):
        return self.nome + " " + self.cognome

    def get_absolute_url(self):
        return reverse("libreria:autore_detail", kwargs={"pk": self.pk})

    class Meta:
        verbose_name = "Autore"
        verbose_name_plural = "Autori"


class Libro_CS(models.Model):
    titolo = models.CharField(max_length=100)
    isbn = models.CharField(max_length=13)
    autore = models.ForeignKey(
        Autore_CS, on_delete=models.CASCADE, related_name="libri")
    genere = models.ManyToManyField(Genere_CS)

    def __str__(self):
        return self.titolo

    class Meta:
        verbose_name = "Libro"
        verbose_name_plural = "Libri"

news/models.py
from django.db import models
from django.db.models.deletion import CASCADE

# Create your models here.


class Giornalista(models.Model):
    # Modello generico di un giornalista #
    nome = models.CharField(max_length=20)
    cognome = models.CharField(max_length=20)

    def __str__(self):
        return self.nome + " " + self.cognome

    class Meta:
        verbose_name = "Giornalista"
        verbose_name_plural = "Giornalisti"


class Articolo(models.Model):
    # Modello generico di un articolo #
    titolo = models.CharField(max_length=100)
    contenuto = models.TextField()
    giornalista = models.ForeignKey(
        Giornalista, on_delete=models.CASCADE, related_name="articoli")

    def __str__(self):
        return self.titolo

    class Meta:
        verbose_name = "Articolo"
        verbose_name_plural = "Articoli"

prima_app/models.py
from django.db import models

# Create your models here.

seconda_app/models.py
from django.db import models

# Create your models here.

libreria/views.py
from django.urls.base import reverse
from libreria.models import Autore_CS, Libro_CS
from django.shortcuts import render
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
# Create your views here.


class AutoreDetail_CS(DetailView):
    model = Autore_CS
    template_name = "dettaglio_autore.html"


class AutoreList_CS(ListView):
    model = Autore_CS
    template_name = "autore_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["autori"] = Autore_CS.objects.all()
        return context


class LibroList_CS(ListView):
    model = Libro_CS
    template_name = "libro_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["libri"] = Libro_CS.objects.all()
        return context

news/views.py
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from .models import Articolo, Giornalista

# Create your views here.


def home(request):
    articoli = Articolo.objects.all()
    giornalisti = Giornalista.objects.all()
    context = {"articoli": articoli, "giornalisti": giornalisti}

    return render(request, "home-news.html", context)


class ArticoloDetailViewCB(DetailView):
    model = Articolo
    template_name = "articolo-detail.html"


class ArticoloListView(ListView):
    model = Articolo
    template_name = "lista-articoli.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["articoli"] = Articolo.objects.all()

        return context


class GiornalistaDetailViewCB(DetailView):
    model = Giornalista
    template_name = "giornalista-detail.html"


class GiornalistaListView(ListView):
    model = Giornalista
    template_name = "lista-giornalisti.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["giornalisti"] = Giornalista.objects.all()

        return context

prima_app/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.


def homepage(request):
    return render(request, "homepage.html")


def menu(request):
    return render(request, "menu.html")


def chisiamo(request):
    return render(request, "chi-siamo.html")


def variabili(request):
    context = {
        "var1": "Variabile numero 1",
        "var2": "Variabile numero 2",
        "var3": "Variabile numero 3",
    }
    return render(request, "variabili.html", context)


def index(request):
    return render(request, "index.html")

seconda_app/views.py
from django.shortcuts import render

# Create your views here.


def esif(request):
    context = {"var1": 5, "var2": 10}
    return render(request, "if.html", context)


def ifelse(request):
    context = {"var1": 10, "var2": 5}
    return render(request, "ifelse.html", context)


def ifelif(request):
    context = {"var1": 10, "var2": 5}
    return render(request, "ifelif.html", context)


def esfor(request):
    context = {"var1": 10}
    return render(request, "for.html", context)

libreria/templates/autore_list.html
{% extends 'base.html' %}
{% block title %} {{block.super}} | Autori
{% endblock title %}
{% block content %}
<h1>Autori</h1>
<br>
{% for autore in autori %}
    <h3><strong>{{autore}}</strong></h3>
    <h5><strong>Nazione: </strong>{{autore.nazione}}</h5>
    <h5><strong>Libri: </strong><a href="{{autore.get_absolute_url}}">Mostra libri</a></h5>
    <hr>
{% endfor %}
{% endblock content %}

libreria/templates/dettaglio_autore.html
{% extends 'base.html'  %}
{% block title %} {{block.super}} | {{autore_cs}}
{% endblock title %}
{% block content %}
<h1>{{autore_cs}}</h1>
<h3><strong>Nazione: </strong>{{autore_cs.nazione}}</h3>
<br>
{% for libro in autore_cs.libri.all %}
    <h4><strong>Titolo: </strong>{{libro.titolo}}</h4>
    <h5><strong>Genere: </strong>{% for genere in libro.genere.all %}{{genere}} {% endfor %}</h5>
    <h5><strong>ISBN: </strong>{{libro.isbn}}</h5>
    <hr>
{% endfor %}
{% endblock content %}

libreria/templates/libro_list.html
{% extends 'base.html'  %}
{% block title %} {{block.super}} | Libreria
{% endblock title %}
{% block content %}
<h1>Libreria</h1>
<br>
{% for libro in libri %}
    <h4><strong>Titolo: </strong>{{libro.titolo}}</h4>
    <h5><strong>Autore: </strong><a href="{{libro.autore.get_absolute_url}}">{{libro.autore}}</a></h5>
    <h5><strong>Genere: </strong>{% for genere in libro.genere.all %}{{genere}} {% endfor %}</h5>
    <h5><strong>ISBN: </strong>{{libro.isbn}}</h5>
    <hr>
{% endfor %}
{% endblock content %}

news/templates/articolo-detail.html
{% extends 'base.html' %}
{% block title %} {{block.super}} | {{ articolo.titolo }} {% endblock title %}
{% block content %}
<h1> {{ articolo.titolo }} </h1>
<h3> {{ articolo.contenuto }} </h3>
<h5> Autore: {{ articolo.giornalista }} </h5>
{% endblock content %}

news/templates/giornalista-detail.html
{% extends 'base.html' %}
{% block title %} {{block.super}} | {{ giornalista.nome }} {{giornalista.cognome}} {% endblock title %}
{% block content %}
<h1> {{ giornalista.nome }} {{giornalista.cognome}} </h1>
{% endblock content %}

news/templates/home-news.html
{% extends 'base.html' %}
{% block title %} {{block.super}} | Articoli e Giornalisti {% endblock title %}
{% block content %}

<h3>Articoli:</h3>
{% for art in articoli %}
<p><strong>Titolo: </strong>{{ art.titolo }}</p>
<p><strong>Contenuto: </strong>{{ art.contenuto }}</p>
<p><strong>Giornalista: </strong>{{ art.giornalista }}</p>
<hr>
{% endfor %}

<h3>Giornalisti:</h3>
{% for gio in giornalisti %}
<p><strong>Nome: </strong>{{ gio.nome }}</p>
<p><strong>Cognome: </strong>{{ gio.cognome }}</p>
{% endfor %}

{% endblock content %}

news/templates/lista-articoli.html
{% extends 'base.html' %}
{% block title %} {{block.super}} | Lista Articoli {% endblock title %}
{% block content %}
<h4>Articoli:</h4>
{% for art in articoli %}
<p> <strong>Titolo: </strong> <a href="/news/articoli/{{ art.id }}"> {{ art.titolo }} </a> </p>
<p> <strong>Contenuto: </strong> {{ art.contenuto }} </p>
<p> <strong>Autore: </strong> {{ art.giornalista }} </p>
<hr>
{% endfor %}
{% endblock content %}

news/templates/lista-giornalisti.html
{% extends 'base.html' %}
{% block title %} {{block.super}} | Lista Giornalisti {% endblock title %}
{% block content %}
<h4>Giornalisti:</h4>
{% for gio in giornalisti %}
<p> <strong>Nome: </strong> {{ gio.nome }} </p>
<p> <strong>Cognome: </strong> <a href="/news/giornalista/{{gio.id}}">{{ gio.cognome }}</a> </p>
<hr>
{% endfor %}
{% endblock content %}

prima_app/templates/chi-siamo.html
{% extends 'base.html' %}
{% block title %} {{block.super}} | Chi siamo {% endblock title %}
{% block content %}
<h1>Chi siamo?</h1>
<p>Siamo noi!</p>
{% endblock content %}

prima_app/templates/homepage.html
{% extends 'base.html' %}
{% block title %} {{block.super}} | Homepage {% endblock title %}
{% block content %} <h1>Benvenuti nella homepage!</h1> {% endblock content %}

prima_app/templates/index.html
{% extends 'base.html' %}
{% block title %} {{block.super}} | Index {% endblock title %}
{% block content %}
<h1>Index</h1>
<ul>
    <li>Prima app</li>
    <ul>
        <li><a href="{% url 'prima_app:homepage' %}">Homepage</a></li>
        <li><a href="{% url 'prima_app:menu' %}">Menu</a></li>
        <li><a href="{% url 'prima_app:chi-siamo' %}">Chi siamo</a></li>
        <li><a href="{% url 'prima_app:variabili' %}">Variabili</a></li>
    </ul>
    <li>Seconda app</li>
    <ul>
        <li><a href="{% url 'seconda_app:if' %}">Esercizio if</a></li>
        <li><a href="{% url 'seconda_app:ifelse' %}">Esercizio if-else</a></li>
        <li><a href="{% url 'seconda_app:ifelif' %}">Esercizio if-elif</a></li>
        <li><a href="{% url 'seconda_app:for' %}">Esercizio for</a></li>
    </ul>
    <li>News</li>
    <ul>
        <li><a href="{% url 'news:homeview' %}">Homepage news</a></li>
        <li><a href="{% url 'news:lista_articoli' %}">Lista articoli</a></li>
        <li><a href="{% url 'news:lista_giornalisti' %}">Lista giornalisti</a></li>
    </ul>
    <li>Libreria</li>
    <ul>
        <li><a href="{% url 'libreria:lista_libri' %}">Lista libri</a></li>
        <li><a href="{% url 'libreria:lista_autori' %}">Lista autori</a></li>
    </ul>
</ul>
{% endblock content %}

prima_app/templates/menu.html
{% extends 'base.html' %}
{% block title %} {{block.super}} | Menu {% endblock title %}
{% block content %}
    <ol>
        <li>Voce numero 1</li>
        <li>Voce numero 2</li>
        <li>Voce numero 3</li>
    </ol>
{% endblock content %}

prima_app/templates/variabili.html
{% extends 'base.html' %}
{% block title %} {{block.super}} | Variabili {% endblock title %}
{% block content %}
    <ol>
        <li>{{var1}}</li>
        <li>{{var2}}</li>
        <li>{{var3}}</li>
    </ol>
{% endblock content %}

primo_progetto/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>{% block title %} Primo progetto {% endblock title %}</title>
</head>

<body>
    {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="/">Primo progetto</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Prima app
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'prima_app:homepage' %}">Homepage</a>
                        <a class="dropdown-item" href="{% url 'prima_app:menu' %}">Menu</a>
                        <a class="dropdown-item" href="{% url 'prima_app:chi-siamo' %}">Chi siamo</a>
                        <a class="dropdown-item" href="{% url 'prima_app:variabili' %}">Variabili</a>
                        <a class="dropdown-item" href="{% url 'prima_app:index' %}">Index</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Seconda app
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'seconda_app:if' %}">Esercizio if</a>
                        <a class="dropdown-item" href="{% url 'seconda_app:ifelse' %}">Esercizio if-else</a>
                        <a class="dropdown-item" href="{% url 'seconda_app:ifelif' %}">Esercizio if-elif</a>
                        <a class="dropdown-item" href="{% url 'seconda_app:for' %}">Esercizio for</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        News
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'news:homeview' %}">Homepage news</a>
                        <a class="dropdown-item" href="{% url 'news:lista_articoli' %}">Lista articoli</a>
                        <a class="dropdown-item" href="{% url 'news:lista_giornalisti' %}">Lista giornalisti</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Libreria
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'libreria:lista_libri' %}">Lista libri</a>
                        <a class="dropdown-item" href="{% url 'libreria:lista_autori' %}">Lista autori</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    {% endblock navbar %}

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>

    <div class="container">
        <br>
        {% block content %}
        {% endblock content %}
    </div>
</body>

</html>

seconda_app/templates/for.html
{% extends 'base.html' %}
{% load static %}
{% load seconda_app %}
{% block title %} {{block.super}} | Esercizio if {% endblock title %}
{% block content %}
    <h1>Risultato</h1>

    <p>var1 = {{var1}}</p>

    {% for i in 0|range:var1 %}
        <p>Giro numero {{i}}</p>
    {% endfor %}
{% endblock content %}

seconda_app/templates/if.html
{% extends 'base.html' %}
{% block title %} {{block.super}} | Esercizio if {% endblock title %}
{% block content %}
    <h1>Risultato</h1>

    <p>var1 = {{var1}}, var2 = {{var2}}</p>

    {% if var1 == var2 %}<p>var1 e var2 sono uguali</p>{% endif %}

    {% if var1 > var2 %}<p>var1 è maggiore di var2</p>{% endif %}

    {% if var1 < var2 %}<p>var1 è minore di var2</p>{% endif %}
{% endblock content %}

seconda_app/templates/ifelif.html
{% extends 'base.html' %}
{% block title %} {{block.super}} | Esercizio if-elif {% endblock title %}
{% block content %}
    <h1>Risultato</h1>
    <p>var1 = {{var1}}, var2 = {{var2}}</p>

    {% if var1 == var2 %}<p>var1 e var2 sono uguali</p>
    {% elif var1 > var2%}<p>var1 è maggiore di var2</p>
    {% else %} <p>var1 è minore di var2</p>
    {% endif %}
{% endblock content %}

seconda_app/templates/ifelse.html
{% extends 'base.html' %}
{% block title %} {{block.super}} | Esercizio if-else {% endblock title %}
{% block content %}
    <h1>Risultato</h1>

    <p>var1 = {{var1}}, var2 = {{var2}}</p>

    {% if var1 == var2 %}
        <p>var1 e var2 sono uguali</p>
    {% else %}
        {% if var1 > var2 %}
            <p>var1 è maggiore di var2</p>
        {% else %}
            <p>var1 è minore di var2</p>
        {% endif %}
    {% endif %}
{% endblock content %}